name: skeleton
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  http: ^0.13.5
  rx_shared_preferences: ^3.0.0
  bloc: ^8.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  english_words: ^4.0.0
  fake_async: ^1.3.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  ios: true
  android: true
  image_path: "assets/logo_square_big.png"
flutter:
  uses-material-design: true
  assets:
    - assets/logo_square_big.png # TODO: add the logo_square_big.png asset file

